version: "2"

services:
#  postgres:
#    image: postgres:9.6
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_DB: app
#      POSTGRES_USER: socrates
#      POSTGRES_PASSWORD: secret
#    volumes:
#      - postgres-data:/var/lib/postgresql/data

  mariadb:
    image: mariadb:10.1
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - mariadb-data:/var/lib/mysql

  redisCommander:
    image: tenstartups/redis-commander
    command: --redis-host redis
    links:
      - redis
    ports:
      - "8081:8081"

  redis:
    image: redis:3.2
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis

volumes:
  postgres-data:
    driver: "local"
  mariadb-data:
    driver: "local"
  redis-data:
    driver: "local"
